export type PlayerPositions={
    id: number ,
    top: number,
    left: number,
    role: string,
    name?: string
}
export type Formation = {
  name: string;
  positions: Omit<PlayerPositions, "name">[]; 
};
export const formations: Formation[]=[
  {
    name: "3-1-4-2",
    positions: [
      { id: 1, top: 95, left: 50, role: "GK" },
      { id: 2, top: 70, left: 75, role: "RCB" },
      { id: 3, top: 75, left: 50, role: "CB" },
      { id: 4, top: 70, left: 25, role: "LCB" },
      { id: 5, top: 60, left: 50, role: "CDM" },
      { id: 6, top: 45, left: 85, role: "RM" },
      { id: 7, top: 45, left: 65, role: "RCM" },
      { id: 8, top: 45, left: 35, role: "LCM" },
      { id: 10, top: 45, left: 15, role: "LM" },
      { id: 9, top: 20, left: 60, role: "ST" },
      { id: 11, top: 20, left: 40, role: "ST" },
    ],
  },
  {
    name: "3-4-3",
    positions: [
    { id: 1, top: 95, left: 50, role: "GK" },
    { id: 2, top: 75, left: 75, role: "RCB" },
    { id: 3, top: 75, left: 50, role: "CB" },
    { id: 4, top: 75, left: 5, role: "LCB" },
    { id: 5, top: 45, left: 85, role: "RM" },
    { id: 6, top: 55, left: 63, role: "RCM" },
    { id: 7, top: 55, left: 33, role: "LCM" },
    { id: 8, top: 45, left: 15, role: "LM" },
    { id: 10, top: 30, left: 75, role: "RW" },
    { id: 9, top: 20, left: 50, role: "CF" },
    { id: 11, top: 30, left: 25, role: "LW" },
  ],
  },
  {
    name: "4-1-2-1-2 (narrow)",
    positions: [
      { id: 1, top: 95, left: 50, role: "GK" },
      { id: 2, top: 75, left: 85, role: "RB" },
      { id: 3, top: 75, left: 65, role: "RCB" },
      { id: 4, top: 75, left: 35, role: "LCB" },
      { id: 5, top: 75, left: 15, role: "LB" },
      { id: 6, top: 60, left: 50, role: "CDM" },
      { id: 7, top: 50, left: 75, role: "RCM" },
      { id: 8, top: 50, left: 25, role: "LCM" },
      { id: 10, top: 37.5, left: 50, role: "CAM" },
      { id: 10, top: 25, left: 65, role: "ST" },
      { id: 9, top: 25, left: 35, role: "ST" },
    ],
  },
  {
    name: "4-5-1",
    positions: [
      { id: 1, top: 95, left: 50, role: "GK" },
      { id: 2, top: 75, left: 85, role: "RB" },
      { id: 3, top: 75, left: 65, role: "RCB" },
      { id: 4, top: 75, left: 35, role: "LCB" },
      { id: 5, top: 75, left: 15, role: "LB" },
      { id: 6, top: 50, left: 90, role: "RM" },
      { id: 7, top: 50, left: 70, role: "RCM" },
      { id: 8, top: 50, left: 50, role: "CM" },
      { id: 9, top: 50, left: 30, role: "LCM" },
      { id: 10, top: 50, left: 10, role: "LM" },
      { id: 11, top:25, left: 50, role: "ST" },
    ],
  },
  {
    name: "4-1-4-1",
    positions: [
      { id: 1, top: 95, left: 50, role: "GK" },
      { id: 2, top: 75, left: 85, role: "RB" },
      { id: 3, top: 75, left: 65, role: "RCB" },
      { id: 4, top: 75, left: 35, role: "LCB" },
      { id: 5, top: 75, left: 15, role: "LB" },
      { id: 6, top: 60, left: 50, role: "CDM" },
      { id: 7, top: 40, left: 85, role: "RM" },
      { id: 8, top: 40, left: 65, role: "RCM" },
      { id: 9, top: 40, left: 35, role: "LCM" },
      { id: 10, top: 40, left: 15, role: "LM" },
      { id: 11, top: 20, left: 50, role: "ST" },
    ],
  },
  {
    name: "4-2-4",
    positions: [
      { id: 1, top: 95, left: 50, role: "GK" },
      { id: 2, top: 75, left: 85, role: "RB" },
      { id: 3, top: 75, left: 65, role: "RCB" },
      { id: 4, top: 75, left: 35, role: "LCB" },
      { id: 5, top: 75, left: 15, role: "LB" },
      { id: 6, top: 50, left: 60, role: "RCM" },
      { id: 7, top: 50, left: 40, role: "LCM" },
      { id: 8, top: 35, left: 85, role: "RW" },
      { id: 9, top: 20, left: 60, role: "ST" },
      { id: 11, top: 20, left: 40, role: "ST" },
      { id: 10, top: 35, left: 15, role: "LW" },
    ],
  },
  {
    name: "4-4-1-1",
    positions: [
      { id: 1, top: 95, left: 50, role: "GK" },
      { id: 2, top: 75, left: 85, role: "RB" },
      { id: 3, top: 75, left: 65, role: "RCB" },
      { id: 4, top: 75, left: 35, role: "LCB" },
      { id: 5, top: 75, left: 15, role: "LB" },
      { id: 6, top: 50, left: 80, role: "RM" },
      { id: 7, top: 50, left: 60, role: "RCM" },
      { id: 8, top: 50, left: 40, role: "LCM" },
      { id: 9, top: 50, left: 20, role: "LM" },
      { id: 10, top: 35, left: 50, role: "CF" },
      { id: 11, top: 20, left: 50, role: "ST" },
    ],
  },
  {
    name: "4-4-2 diamond",
    positions: [
      { id: 1, top: 95, left: 50, role: "GK" },
      { id: 2, top: 75, left: 85, role: "RB" },
      { id: 3, top: 75, left: 65, role: "RCB" },
      { id: 4, top: 75, left: 35, role: "LCB" },
      { id: 5, top: 75, left: 15, role: "LB" },
      { id: 6, top: 60, left: 50, role: "CDM" },
      { id: 7, top: 45, left: 65, role: "RCM" },
      { id: 8, top: 45, left: 35, role: "LCM" },
      { id: 9, top: 32.5, left: 50, role: "CAM" },
      { id: 10, top: 20, left: 65, role: "ST" },
      { id: 11, top: 20, left: 35, role: "ST" },
    ],
  },
  {
    name: "5-4-1",
    positions: [
      { id: 1, top: 95, left: 50, role: "GK" },
      { id: 2, top: 65, left: 90, role: "RWB" },
      { id: 3, top: 75, left: 70, role: "RCB" },
      { id: 4, top: 75, left: 50, role: "CB" },
      { id: 5, top: 75, left: 30, role: "LCB" },
      { id: 6, top: 65, left: 10, role: "LWB" },
      { id: 7, top: 45, left: 75, role: "RM" },
      { id: 8, top: 60, left: 50, role: "RCM" },
      { id: 9, top: 35, left: 50, role: "LCM" },
      { id: 10, top: 45, left: 25, role: "LM" },
      { id: 11, top: 20, left: 50, role: "ST" },
    ],
  },
  {
    name: "5-3-2",
    positions: [
      { id: 1, top: 95, left: 50, role: "GK" },
      { id: 2, top: 65, left: 90, role: "RWB" },
      { id: 3, top: 75, left: 70, role: "RCB" },
      { id: 4, top: 75, left: 50, role: "CB" },
      { id: 5, top: 75, left: 30, role: "LCB" },
      { id: 6, top: 65, left: 10, role: "LWB" },
      { id: 7, top: 45, left: 73, role: "RCM" },
      { id: 8, top: 45, left: 50, role: "CM" },
      { id: 10, top: 45, left: 27, role: "LCM" },
      { id: 9, top: 23, left: 60, role: "ST" },
      { id: 11, top: 23, left: 40, role: "ST" },
    ],
  },
  {
    name: "4-3-3",
    positions: [
      { id: 1, top: 95, left: 50, role: "GK" },
      { id: 2, top: 75, left: 85, role: "RB" },
      { id: 3, top: 75, left: 65, role: "RCB" },
      { id: 4, top: 75, left: 35, role: "LCB" },
      { id: 5, top: 75, left: 15, role: "LB" },
      { id: 6, top: 55, left: 65, role: "RCM" },
      { id: 7, top: 38, left: 50, role: "CM" },
      { id: 8, top: 55, left: 35, role: "LCM" },
      { id: 9, top: 27, left: 80, role: "RW" },
      { id: 10, top: 20, left: 50, role: "ST" },
      { id: 11, top: 27, left: 20, role: "LW" },
    ],
  }
]
